version: '3.8'
  
services:
  api:
    container_name: api_container
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - api_network
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    container_name: db_container
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./start.sh:/docker-entrypoint-initdb.d/start.sh
    ports:
      - "5432:5432"
    networks:
      - api_network
    restart: unless-stopped
    env_file: .env

networks:
  api_network: {}
  
volumes:
  postgres:
