version: '3.8'
services:
  postgres_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./start.sh:/docker-entrypoint-initdb.d/start.sh
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  api:
    container_name: api
    build: .
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - postgres_db
    volumes:
      - .:/app

networks:
  default:
       name: api_network
